#include "hal_data.h"
#include "stdio.h"

#include "RTT/SEGGER_RTT.h"


#define BUFF_SIZE     (16U)
#define INITIAL_VAL  '\0'
#define TIMER_UNITS_MS (1000U)
#define CLOCK_TYPE_SP  (1ULL)

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

void AGT0_Callback(timer_callback_args_t *p_args)
{
    if(p_args->event == TIMER_EVENT_CYCLE_END)
    {
        SEGGER_RTT_WriteString(0, "AGT0\r\n");
    }
}

void GPT0_Callback(timer_callback_args_t *p_args)
{
    if(p_args->event == TIMER_EVENT_CYCLE_END)
    {
        SEGGER_RTT_WriteString(0, "GPT0\r\n");
    }
}

void change_Period()
{
    uint64_t period_counts;
    uint32_t pclkd_freq_hz;
    uint32_t value;
    unsigned char read_data[BUFF_SIZE] = {INITIAL_VAL};
    int r = 0;

    SEGGER_RTT_WriteString(0, "\r\n Enter the desired perion in milisecond \r\n");
    do
    {
        read_data[r] = (unsigned char)SEGGER_RTT_WaitKey();
        if((read_data[r] < 0x30) || (read_data[r] > 0x39))
        {
            read_data[r] = INITIAL_VAL;
            break;
        }
        r++;
    }
    while(r<BUFF_SIZE);
    value = (uint32_t)(atoi((char*)read_data));

    pclkd_freq_hz = R_FSP_SystemClockHzGet(FSP_PRIV_CLOCK_PCLKB);
    pclkd_freq_hz >>=(uint32_t)(gpt_timer0_periodic_cfg.source_div);

    period_counts = (uint64_t)((value * (pclkd_freq_hz * CLOCK_TYPE_SP)) / TIMER_UNITS_MS);

    R_GPT_PeriodSet(&gpt_timer0_periodic_ctrl, (uint32_t)period_counts);

}

void Period_Init(void)
{
    R_GPT_Open(&gpt_timer0_periodic_ctrl, &gpt_timer0_periodic_cfg);
    R_GPT_Start(&gpt_timer0_periodic_ctrl);

    R_GPT_Open(&gpt_timer0_pwm_ctrl, &gpt_timer0_pwm_cfg);
    R_GPT_Start(&gpt_timer0_pwm_ctrl);
}

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
    SEGGER_RTT_WriteString(0, "SEGGER RTT Terminal\r\n");
    SEGGER_RTT_ConfigUpBuffer(0, NULL, NULL, 0, SEGGER_RTT_MODE_NO_BLOCK_SKIP);

    Period_Init();

    R_AGT_Open(&agt_timer0_ctrl, &agt_timer0_cfg);
    R_AGT_Start(&agt_timer0_ctrl);


    while(1)
    {
        change_Period();
        R_BSP_SoftwareDelay(1000, BSP_DELAY_UNITS_MILLISECONDS);
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, g_ioport.p_cfg);
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
